# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
name: personal-os
description: This is my personal OS image.
base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: 44
modules:
  - type: files
    files:
      - source: system
        destination: /
  # add terra repo, remove when secureblue/secureblue/issues/2210 is closed
  - type: script
    snippets:
      - "dnf install --assumeyes --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release"
  - type: dnf
    install:
      packages:
        - starship
        - crun-krun
  - from-file: sway.yml
  - from-file: thunderbolt.yml
  - from-file: canon-printer.yml
  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - eu.betterbird.Betterbird
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
