# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
#
name: personal-os
description: This is my personal OS image.
base-image: ghcr.io/secureblue/sericea-main-hardened
image-version: 44
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      copr:
        - name: atim/starship
          chroot: fedora-44-x86_64
    install:
      packages:
        - micro
        - starship
        - crun-krun
  - from-file: sway.yml
  - from-file: thunderbolt.yml
  - from-file: canon-printer.yml
  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - eu.betterbird.Betterbird
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
